"""
Type Definitions for Visual Emotion Loop System
================================================

This module defines the core data structures for the emotion-aware
cashier conversation system.

Key Types:
    - EmotionType: Enum of supported emotions (Happy, Neutral, Sad)
    - Emotion: Single emotion detection with valence/arousal
    - ConversationTurn: One round of the visual loop
    - ConversationState: Full session state with history
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, List


class EmotionType(Enum):
    """
    Supported emotion types for the visual loop.

    These map to the ConvNeXt classifier outputs.
    """

    POSITIVE = "Positive"
    NEUTRAL = "Neutral"
    NEGATIVE = "Negative"


@dataclass
class Emotion:
    """
    Single emotion detection from webcam frame.

    Attributes:
        emotion_type: Classified emotion category
        valence: Positive/negative dimension (1-10 scale)
        arousal: Energy/activation level (1-10 scale)
        timestamp: When this emotion was detected
    """

    emotion_type: EmotionType
    valence: float
    arousal: float
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class ConversationTurn:
    """
    Single round of the visual emotion loop.

    Note: 'visual_context' replaces traditional 'user_input' since
    this is a visual-only system with no text from the user.

    Attributes:
        visual_context: Description of what was observed (e.g., "[Visual: HAPPY]")
        agent_response: Text generated by Gemini for Furhat to speak
        emotion: Detected emotion for this turn
        round_number: Which round of the conversation
        timestamp: When this turn occurred
    """

    user_input: str  # Actually visual context like "[Visual: HAPPY]"
    agent_response: str
    emotion: Emotion
    round_number: int
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class ConversationState:
    """
    Full state of a visual emotion loop session.

    This tracks the entire conversation from when a customer approaches
    until they leave or the session times out.

    Attributes:
        session_id: Unique identifier for this session
        current_emotion: Most recently detected emotion
        emotion_history: All emotions detected during session
        conversation_history: All turns (agent responses + emotions)
        conversation_round: Current round number (0-indexed)
        user_input: Legacy field (stores visual context in visual mode)
        agent_response: Most recent agent response
        is_complete: Whether session has ended
        started_at: When session began

    Termination Conditions:
        - Max duration: 120 seconds
        - Max rounds: 10 turns
    """

    session_id: str = ""
    current_emotion: Optional[Emotion] = None
    emotion_history: List[Emotion] = field(default_factory=list)
    conversation_history: List[ConversationTurn] = field(default_factory=list)
    conversation_round: int = 0
    user_input: str = ""  # Visual context in visual mode
    agent_response: str = ""
    is_complete: bool = False
    started_at: datetime = field(default_factory=datetime.now)

    # Payment tracking
    payment_method: Optional[str] = None  # "cash" or "card"
    total_amount: float = 0.0  # Total in SEK
    customer_speech: str = ""  # What the customer said (speech-to-text)
    asked_payment: bool = False  # Whether we've asked cash or card
    
    # Item lookup tracking
    looking_up_item: bool = False  # Whether we're looking up a missing item
    item_found: Optional[bool] = None  # Result of lookup (True/False/None)
    
    def add_emotion(self, emotion: Emotion) -> None:
        """Record a detected emotion."""
        self.emotion_history.append(emotion)
        self.current_emotion = emotion

    def add_turn(self, user_input: str, agent_response: str, emotion: Emotion) -> None:
        """
        Record a complete conversation turn.

        Args:
            user_input: Visual context (e.g., "[Visual: HAPPY]")
            agent_response: Gemini-generated text for Furhat
            emotion: Detected emotion for this turn
        """
        turn = ConversationTurn(
            user_input=user_input,
            agent_response=agent_response,
            emotion=emotion,
            round_number=self.conversation_round,
        )
        self.conversation_history.append(turn)
        self.user_input = user_input
        self.agent_response = agent_response
        self.current_emotion = emotion

    def get_last_turn(self) -> Optional[ConversationTurn]:
        """Get the most recent conversation turn."""
        return self.conversation_history[-1] if self.conversation_history else None

    def elapsed_seconds(self) -> float:
        """Get seconds since session started."""
        return (datetime.now() - self.started_at).total_seconds()

    def should_terminate(
        self, max_duration_seconds: int = 120, max_rounds: int = 10
    ) -> bool:
        """
        Check if the session should end.

        Args:
            max_duration_seconds: Maximum session length (default 120s)
            max_rounds: Maximum conversation rounds (default 10)

        Returns:
            True if session should end
        """
        if self.elapsed_seconds() > max_duration_seconds:
            return True
        if self.conversation_round >= max_rounds:
            return True
        return False

    def get_emotion_trend(self, last_n: int = 3) -> List[EmotionType]:
        """
        Get the recent emotion trend.

        Useful for detecting if customer mood is improving or declining.
        """
        recent = self.emotion_history[-last_n:] if self.emotion_history else []
        return [e.emotion_type for e in recent]
